version: '2'
services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - "./tomcat/webapps:/usr/local/tomcat/webapps"
      - "./tomcat/logs:/usr/local/tomcat/logs"
    networks:
      - public
 
networks:
  public:
    driver: bridge
    

