version: '2'
services:
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    volumes:
      - "./www/phpmyadmin:/var/www/html"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - public 
 
networks:
  public:
    driver: bridge
    
