version: '2'
services:
   mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./var/log/mysql/:/var/log/mysql"
    networks:
      - public
 
networks:
  public:
    driver: bridge
    
