version: '2'
services:
   mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql #数据文件挂载
      - ./etc/mysql/conf.d:/etc/mysql/conf.d #配置文件挂载
      - ./var/log/mysql:/var/log/mysql #日志文件挂载
    networks:
      - public
 
networks:
  public:
    driver: bridge
    
