version: '2'
services:
  lnp:
    image: haohonglong/lnmp:1.1
    ports:
      - "80:80"
      - "8083:8080"
      - "27017:27017"
    depends_on:
       - "mysql"
    volumes:
      - "/Users/long/sites:/usr/local/nginx/html"
      - "/usr/local/var/nginx:/etc/nginx"
      - "./data/log:/var/log"
      - "./data/mongodb:/data/db"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - "/usr/local/var/mysql:/var/lib/mysql"
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysql  
    
