version: '2'
services:
  node:
    image: haohonglong/node:1.0
    container_name: node
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 9527:9527
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    extra_hosts:
       - "yaf.local:172.21.0.4"
       - "boda.api:192.168.0.104"
    networks:
      - public
    command: bash
    tty: true

networks:
  public:
    driver: bridge
    
