version: '2'
services:
  lnp:
    image: haohonglong/lnmp:1.1
    container_name: lnp
    restart: always
    ports:
      - "80:80"
      - "8083:8080"
      - "27017:27017"
    depends_on:
      - "mysql"
    volumes:
      - "./etc/php:/etc/php"
      - "./www:/usr/local/nginx/html"
      - "./etc/nginx:/etc/nginx"
      - "./data/log:/var/log"
      - "./data/mongodb:/data/db"
    working_dir: /www
    networks:
      - public
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql #数据文件挂载
      - ./etc/mysql/conf.d:/etc/mysql/conf.d #配置文件挂载
      - ./var/log/mysql:/var/log/mysql #日志文件挂载
    networks:
      - public
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - "./www/phpmyadmin:/var/www/html"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    networks:
      - public 
  node:
    image: haohonglong/node:1.0
    container_name: node
    ports:
      - 9527:9527
      - 3001:3000
      - 3002:3002
      - 9528:9528
    depends_on:
      - "mysql"
    #links:
      #- "mysql"
    volumes:
      - ./app:/app
      #- ./bin:/usr/local/lib/node
    working_dir: /app
    networks:
      - public
    command: bash
    tty: true

  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-password
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    volumes:
      - ./data/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/data:/data
      - ./data/redis/etc/redis-password:/run/secrets/redis-password
    networks:
      - public
    ports:
      - "6397:6379"



networks:
  public:
    driver: bridge
    
