version: '2'
services:
  node:
    image: haohonglong/node:1.0
    container_name: node
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004
    volumes:
      - ./app:/app
    working_dir: /app
    extra_hosts:
      - "yaf.local:192.168.0.105"
      - "boda.api:192.168.0.105"
    networks:
      - public
    command: bash
    tty: true


networks:
  public:
    driver: bridge
    
