version: '2'
services:
  lnp:
    image: haohonglong/lnmp:1.1
    container_name: lnp
    restart: always
    ports:
      - "80:80"
      - "8083:8080"
      - "27017:27017"
    volumes:
      - "./etc/php:/etc/php"
      - "./www:/usr/local/nginx/html"
      - "./etc/nginx:/etc/nginx"
      - "./data/log:/var/log"
      - "./data/mongodb:/data/db"
    working_dir: /www
    environment:
      - TZ=Asia/Shanghai
    networks:
      - public

networks:
  public:
    driver: bridge
    
