version: '2'
services:
  node:
    image: haohonglong/node:1.0
    container_name: node
    ports:
      - 9527:9527
      - 3001:3000
      - 3002:3002
      - 9528:9528
    depends_on:
      - "mysql"
    #links:
      #- "mysql"
    volumes:
      - ./app:/app
      #- ./bin:/usr/local/lib/node
    working_dir: /app
    networks:
      - public
    command: bash
    tty: true

networks:
  public:
    driver: bridge
    
