version: '2'
services:
  baota:
    image: pch18/baota
    container_name: baota
    restart: always
    privileged: true
    shm_size: '1gb'
    ports:
      - "8888:8888"
      - "888:888"
    volumes:
      - "./baota/wwwroot:/www/wwwroot"
    networks:
      - public


networks:
  public:
    driver: bridge
    
