version: "3"
services:
  gcc:
    image: gcc:11.5.0
    container_name: gcc
    hostname: gcc
    environment:
      TZ: "$TZ"
      HOSTIP: $HOST_IP
    restart: always
    command: ["bash"]
    tty: true
    working_dir: /app
    volumes:
      - "/home/vagrant/projects/gcc/exercise_of_c:/app"
    networks:
      - default


networks:
  default:
    driver: bridge

