version: "3"
services:
  rust:
    image: haohonglong/nvm:version1.0
    container_name: rust
    hostname: rust
    environment:
      TZ: "$TZ"
      HOSTIP: $HOST_IP
    ports:
      - 7878:7878
    volumes:
      - /www/lamborghiniJS/LAM2-demos:/www/:rw
      - ./init.sh:/init.sh:rw
    working_dir: /www/tools/build
    stdin_open: true
    tty: true
    networks:
      - default

networks:
  default:
    driver: bridge

